#include <smk/Window.hpp>
#include <smk/BlendMode.hpp>
//#include <smk/CircleShape.hpp>
#include <smk/Color.hpp>
//#include <smk/ConvexShape.hpp>
#include <smk/Drawable.hpp>
#include <smk/Font.hpp>
//#include <smk/Glyph.hpp>
//#include <smk/Image.hpp>
//#include <smk/PrimitiveType.hpp>
//#include <smk/Rect.hpp>
//#include <smk/RectangleShape.hpp>
//#include <smk/RenderStates.hpp>
#include <smk/RenderTarget.hpp>
//#include <smk/RenderTexture.hpp>
//#include <smk/RenderWindow.hpp>
#include <smk/Shader.hpp>
#include <smk/Shape.hpp>
#include <smk/Sprite.hpp>
#include <smk/Text.hpp>
#include <smk/Texture.hpp>
//#include <smk/Transform.hpp>
#include <smk/Transformable.hpp>
#include <smk/Vertex.hpp>
#include <smk/VertexArray.hpp>
//#include <smk/VertexBuffer.hpp>
#include <smk/View.hpp>
#include <DungeonEscape/Vector.h>
#include <DungeonEscape/Rect.h>