name: Linux CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code including submodules
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential zip libxrandr-dev libglew-dev udev libudev-dev libopenal-dev libvorbis-dev libflac-dev

    - name: Configure and build with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --verbose

    - name: Zip artifacts
      run: |
        cd build
        zip -r ../release_linux.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release_linux
        path: release_linux.zip
