name: Windows CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code including submodules
      uses: actions/checkout@v2
      with:
        submodules: 'true' 

    - name: Configure and build with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --verbose
        cd bin/Release
        move resources Debug


    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release_windows
        path: build/bin/Release/Debug
